# codecov.yml - Codecov Configuration
# Purpose: Visualization + PR comments + trending, but NO enforced CI requirements

coverage:
  # Coverage display precision
  precision: 2      # Show 2 decimal places, e.g., 85.42%
  round: down       # Round down, e.g., 85.99% → 85.99%
  range: 70..100    # Color range: 70% (red) → 100% (green)

  # Coverage status configuration (informational only, won't block CI)
  status:
    project:
      default:
        target: auto          # Auto target: compare with previous commit
        informational: true   # Informational only: won't fail CI

    patch:
      default:
        target: auto          # Auto target: compare new code with project average
        informational: true   # Informational only: won't fail CI

# Paths excluded from coverage calculation
ignore:
  # ===== Ent ORM generated code =====
  - "internal/adapter/storage/ent/migrate/migrations/*.sql"  # Migration files
  - "cmd/*/main.go"                                 # Main entry points

# PR comment configuration - Show detailed coverage information in PRs
comment:
  require_changes: false        # Show comment even if coverage hasn't changed
  layout: "reach,diff,flags,files,footer"  # Full layout:
                                           #   - reach: Overall coverage
                                           #   - diff: Coverage changes
                                           #   - flags: Flag classifications
                                           #   - files: File list
                                           #   - footer: Codecov link
  behavior: default             # Update existing comment
  require_base: false           # Don't require base branch data
  require_head: true            # Require current branch data

# Flags configuration - Categorize different types of tests
flags:
  unittests:
    paths:
      - internal/               # Only include internal directory
    carryforward: false         # Don't use previous coverage data
    # Note: No target set, so no enforced coverage requirement

# ===== Configuration Explanation =====
#
# Key setting: informational: true
# - Makes Codecov status checks "informational only"
# - GitHub will show coverage status, but won't block PR merging
# - You can see coverage changes, but CI won't fail because of it
#
# target: auto
# - Auto-compare with previous commit instead of fixed target
# - Shows trends without hard requirements
#
# No threshold setting
# - Removed to avoid validation errors
# - Without threshold, coverage drops won't fail CI
#
# ===== What You Get =====
# ✅ Codecov Dashboard: Coverage trends, file-level details, historical data
# ✅ PR Comments: Detailed coverage changes, file lists, uncovered lines
# ✅ GitHub Status: Shows coverage info, marked as "Informational"
# ✅ Flag Classification: See unittest coverage separately
# ✅ Accurate Stats: Real coverage after excluding Ent generated code
# ❌ Won't Block: CI won't fail due to coverage issues
