# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: things3

builds:
  - id: things3
    dir: cmd/things3
    binary: things3
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/moond4rk/things3/cmd/things3/cmd.version={{.Version}}
      - -X github.com/moond4rk/things3/cmd/things3/cmd.commit={{.Commit}}
      - -X github.com/moond4rk/things3/cmd/things3/cmd.buildDate={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_macos_{{ if eq .Arch \"arm64\" }}m1{{ else }}intel{{ end }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^chore: release"

release:
  github:
    owner: moonD4rk
    name: things3
  draft: false
  prerelease: auto

brews:
  - name: things3
    homepage: "https://github.com/moonD4rk/things3"
    description: "CLI for Things 3 task manager on macOS"
    license: "Apache-2.0"
    directory: Formula
    skip_upload: auto
    repository:
      owner: moonD4rk
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "github-actions[bot]"
      email: "github-actions[bot]@users.noreply.github.com"
    commit_msg_template: "brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "things3"
    test: |
      system "#{bin}/things3", "version"
    caveats: |
      things3 requires read access to the Things 3 database.
      Make sure Things 3 is installed on your Mac.
