# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: things3

builds:
  - id: things3
    dir: cmd/things3
    binary: things3
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/moond4rk/things3/cmd/things3/cmd.version={{.Version}}
      - -X github.com/moond4rk/things3/cmd/things3/cmd.commit={{.Commit}}
      - -X github.com/moond4rk/things3/cmd/things3/cmd.buildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS{{else}}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}Intel{{ else if eq .Arch "arm64" }}Apple_Silicon{{ else }}{{ .Arch }}{{ end }}

checksum:
  disable: true

changelog:
  use: github
  sort: asc

release:
  github:
    owner: moonD4rk
    name: things3
  draft: false
  prerelease: auto
